"""add _phone_column

Revision ID: 939b19cf3813
Revises: c560b3236d04
Create Date: 2023-04-14 14:38:47.209781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939b19cf3813'
down_revision = 'c560b3236d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone')
    # ### end Alembic commands ###
