"""Auto_create_vote_table

Revision ID: c560b3236d04
Revises: 328f140eb115
Create Date: 2023-04-14 14:07:20.203677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c560b3236d04'
down_revision = '328f140eb115'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.add_column('User', sa.Column('Email', sa.String(), nullable=False))
    op.drop_constraint('User_email_key', 'User', type_='unique')
    op.drop_column('User', 'email')
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('User', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('User_email_key', 'User', ['email'])
    op.drop_column('User', 'Email')
    op.drop_table('Votes')
    # ### end Alembic commands ###
